NUMPY INTRO

In [110]:
import numpy as np

In [4]:
n1=np.array([1,2,3,4])
n1

array([1, 2, 3, 4])

In [7]:
type(n1)

numpy.ndarray

In [14]:
n2=np.array([[1,2],[10,20]])
n2



array([[ 1,  2],
       [10, 20]])

In [16]:
type(n2)

numpy.ndarray

In [18]:
n3=np.zeros((3,3))

In [20]:
n3

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [21]:
n4=np.full((3,3),(1))

In [23]:
n4

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [26]:
n5=np.arange(10,20)
n5

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [28]:
n6=np.arange(1,10,3)
n6

array([1, 4, 7])

In [30]:
n7=np.random.randint(1,100,10)
n7

array([ 9, 61, 43, 61, 84,  2, 40, 62, 73, 50])

In [31]:
# 10 is size here

In [34]:
#krejnbg

In [35]:
n8=np.array([[1,2,3],[10,20,30]])


Changing the dimensions (shape) of the array

In [38]:
n8.shape

(2, 3)

In [42]:
n8.shape=(3,2)
n8

array([[ 1,  2],
       [ 3, 10],
       [20, 30]])

In [44]:
n1=[1,2,3]
n2=[4,5,6]

Ways to add(stack) arrays

In [49]:
np.vstack((n1,n2))

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
np.hstack((n1,n2))

array([1, 2, 3, 4, 5, 6])

In [53]:
np.column_stack((n1,n2))


array([[1, 4],
       [2, 5],
       [3, 6]])

Intersection and Difference

In [ ]:


n1=[2,3,4]
np.intersect1d(n1,n2)


np.setdiff1d(n1,n2)

In [63]:
np.setdiff1d(n2,n1)

array([5, 6])

In [66]:
np.sum([n1,n2])


24

In [70]:
np.sum([n1,n2],axis=1)

array([ 9, 15])

In [77]:
n1


[2, 3, 4]

In [82]:
n12=np.array([10,20,30])
n12

array([10, 20, 30])

In [91]:
n12=n12+5

In [93]:
n12

array([15, 25, 35])

In [95]:
n12=n12-3
n12

array([ 9, 19, 29])

In [97]:
n12=n12*2
n12


array([ 36,  76, 116])

In [98]:
n12=n12/3
n12

array([12.        , 25.33333333, 38.66666667])

In [100]:
n12-4


array([ 8.        , 21.33333333, 34.66666667])


Next up, mean, median and standard deviation

In [103]:
n20=np.array([1,2,3,4,5,6])
np.mean(n20)

3.5

In [104]:
np.std(n1)

0.816496580927726

In [105]:
np.median(n1)

3.0

Numpy Save and Load Array


In [107]:
np.save('my_numpy',n1)

In [109]:
n2=np.load('my_numpy.npy')
n2

array([2, 3, 4])